WebMVC/Controllers/BGVSController.cs
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System;
using System.Net;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using PagedList;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.IO;
using Data;


namespace WebMVC.Controllers
{
    public class BGVSController : Controller
    {
        //
        // GET: /BGVS/
        private MTDTEntities db = new MTDTEntities();
        public ActionResult Index()
        {
            var lst_bgvs = db.Database.SqlQuery<BANGGIAVESINH>("Exec GetBGVS_Cond").ToList();
            return View(lst_bgvs);
        }
        public EmptyResult ThemBGVS(string tenbgvs, decimal thanhtienvs)
        {
            db.Database.ExecuteSqlCommand("InsertBGVS @tenbgvs={0}, @thanhtienvs={1}", tenbgvs, thanhtienvs);
            return new EmptyResult();
        }
        public EmptyResult UpdateBGVS(int idbgvs, string tenbgvs, decimal thanhtienvs)
        {
            db.Database.ExecuteSqlCommand("UpdateBGVS @idbgvs={0}, @tenbgvs={1}, @thanhtienvs={2}", idbgvs, tenbgvs, thanhtienvs);
            return new EmptyResult();
        }   
     
        public EmptyResult XoaBGVS(int id)
        {
            db.Database.ExecuteSqlCommand("DeleteBGVS @idbgvs={0}", id);
            return new EmptyResult();
        }
	}
}

WebMVC/Controllers/DuongController.cs
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System;
using System.Net;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using PagedList;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.IO;
using Data;


namespace WebMVC.Controllers
{
    public class DuongController : Controller
    {
        //
        // GET: /HTTT/
        private MTDTEntities db = new MTDTEntities();
        public ActionResult Index()
        {
            var lst_kv = db.Database.SqlQuery<KHUVUC>("Exec KhuvucSelect");
            if (User.IsInRole("ReadOnly"))
                return Content("<script language='javascript' type='text/javascript'>alert('Bạn không có quyền thực hiện thao tác này')</script>");
            else
                return View(lst_kv);
        }
        public ActionResult Duong(string khuvuc, string currentFilter, string searchString, int? page)
        {
            if (searchString != null)
            { page = 1; }
            else
            { searchString = currentFilter; }
            ViewBag.CurrentFilter = searchString;
            
            int pageSize = 20;
            int pageNumber = (page ?? 1);
            ViewBag.CurrentPage = page;
            ViewBag.khuvuc = khuvuc;
            ViewBag.tenkhuvuc = db.getKhuvucbyMakhuvuc(khuvuc).Select(a => a.TENKHUVUC).FirstOrDefault();

            var lst_duong = db.Database.SqlQuery<DUONG>("getDuongbyKhuvuc @i_makhuvuc={0}, @i_searchstring={1}", khuvuc, searchString).ToPagedList(pageNumber, pageSize);
            return View(lst_duong);
        }
        public EmptyResult ThemDuong(string makhuvuc, string tenduong)
        {
            db.Database.ExecuteSqlCommand("InsertDuong @makhuvuc={0}, @tenduong={1}", makhuvuc, tenduong);
            return new EmptyResult();
        }
        public EmptyResult UpdateDuong(int idduong, string tenduong)
        {
            db.Database.ExecuteSqlCommand("UpdateDuong @idduong={0}, @tenduong={1}", idduong, tenduong);
            return new EmptyResult();
        }

        public JsonResult XoaDuong(int id)
        {
            var result = db.Database.ExecuteSqlCommand("DeleteDuong @idduong={0}", id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
	}
}

WebMVC/Controllers/HDDTController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Data;
using PagedList;
using Data.ViewModels;
using System.Threading.Tasks;
using WebMVC.InvoiceServices;
using Newtonsoft.Json;
using Microsoft.Reporting.WebForms;
using System.Data.SqlClient;
using System.Data;
using System.Web.UI.WebControls;
using System.IO;

namespace WebMVC.Controllers
{
    public class HDDTController : Controller
    {
        MTDTEntities db = new MTDTEntities();
        private PublishService.PublishServiceSoapClient publishServiceClient = new PublishService.PublishServiceSoapClient();
        private BusinessService.BusinessServiceSoapClient businessServiceClient = new BusinessService.BusinessServiceSoapClient();
        private PortalService.PortalServiceSoapClient portalServiceSoapClient = new PortalService.PortalServiceSoapClient();
        string Username = "";
        string Password = "";
        string Account = "";
        string ACpass = "";
        string Pattern = "";
        string Serial = "";
        List<HINHTHUCTT> hinhThucs;
        List<BANGGIAVESINH> services;
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        #region Phát hành hóa đơn
        [Authorize]
        public ActionResult PhatHanh()
        {
            return View();
        }
        [Authorize]
        public ActionResult PhatHanhHoaDon(string chuky, int? page, int? pagesize, string currentFilter, string searchString, string khuvuc, int duong, string soghi, string loaihoadon, string httt, string status, int lh28k)
        {
            db = new MTDTEntities();
            if (searchString != null)
            { page = 1; }
            else
            { searchString = currentFilter; }
            ViewBag.CurrentFilter = searchString;
            chuky = chuky == "0" ? "1" : chuky;
            db.Database.ExecuteSqlCommand("InsertTimKiemKhachHang @chuky={0}, @khuvuc={1}, @duong={2}, @soghi={3}", chuky, khuvuc, duong, soghi);

            int pageSize = 50;
            if (pagesize.HasValue)
            {
                pageSize = (int)pagesize;
            }
            ViewBag.pagesize = pageSize;
            int pageNumber = (page ?? 1);
            ViewBag.CurrentPage = page;
            ViewBag.chuky = chuky;
            ViewBag.khuvuc = khuvuc;
            ViewBag.duong = duong;
            ViewBag.soghi = soghi;
            ViewBag.loaihoadon = loaihoadon;
            ViewBag.httt = httt;
            ViewBag.status = status;
            ViewBag.searchString = searchString;
            ViewBag.lh28k = lh28k;
            var lst_hd = db.Database.SqlQuery<GetHoaDonJoinLastInvoice>("Exec GetHoaDonJoinLastInvoice @i_searchstring={0}, @i_status ={1}, @i_isLh28k ={2}", searchString, status, lh28k).ToPagedList(pageNumber, pageSize);
            ViewBag.HDDTs = lst_hd;
            return View("PhatHanh", lst_hd);
        }
        [Authorize]
        public async Task<string> PhatHanhHoaDons(string[] selectedHoadons)
        {
            List<GetHoaDonJoinLastInvoice> hoaDons = new List<GetHoaDonJoinLastInvoice>();
            List<SelectedHoaDon> _selectedHoadons = new List<SelectedHoaDon>();
            foreach (var hoadon in selectedHoadons)
            {
                var index = hoadon.IndexOf("|");
                string chuKyNo = hoadon.Substring(0, index);
                string msCoDinh = hoadon.Substring(index + 1);
                SelectedHoaDon selectedHoadon = new SelectedHoaDon(chuKyNo, msCoDinh);
                _selectedHoadons.Add(selectedHoadon);
            }

            foreach (var hoadon in _selectedHoadons)
            {
                var hd = db.TIMKIEMKHACHHANGs.SingleOrDefault(n => n.CHUKYNO == hoadon.chuKyNo && n.MASOCD == hoadon.msCoDinh);
                hoaDons.Add(new GetHoaDonJoinLastInvoice(hd));
            }
            string phatHanhResult = await PhatHanhHDDT(hoaDons);
            return phatHanhResult;

        }
        [Authorize]
        public async Task<string> PhatHanhTatCa(string chuky, string searchString, string khuvuc, int duong, string soghi, string status, int lh28k)
        {
            db.Database.ExecuteSqlCommand("InsertTimKiemKhachHang @chuky={0}, @khuvuc={1}, @duong={2}, @soghi={3}", chuky, khuvuc, duong, soghi);
            var lst_hd = db.Database.SqlQuery<GetHoaDonJoinLastInvoice>("Exec GetHoaDonJoinLastInvoice @i_searchstring={0}, @i_status ={1}, @i_isLh28k ={2}", searchString, status, lh28k).ToList();

            //string phatHanhResult = await PhatHanhHDDT(lst_hd.Skip(0).Take(2500).ToList());
            string phatHanhResult = await PhatHanhHDDT(lst_hd.ToList());
            return phatHanhResult;
            //return "";
        }
        [Authorize]
        public async Task<string> ThanhToanTatCa(string chuky, string searchString, string khuvuc, int duong, string soghi, string status, int lh28k)
        {
            db.Database.ExecuteSqlCommand("InsertTimKiemKhachHang @chuky={0}, @khuvuc={1}, @duong={2}, @soghi={3}", chuky, khuvuc, duong, soghi);
            var lst_hd = db.Database.SqlQuery<GetHoaDonJoinLastInvoice>("Exec GetHoaDonJoinLastInvoice @i_searchstring={0}, @i_status ={1}, @i_isLh28k ={2}", searchString, status, lh28k).ToList();

            //string phatHanhResult = await PhatHanhHDDT(lst_hd.Skip(0).Take(2500).ToList());
            List<string> keys = new List<string>();
            foreach(var hoaDon in lst_hd)
            {
                keys.Add(hoaDon.KEY);
            }
            List<string> confirmResults = await ConfirmHoaDons(keys);
            foreach(var key in confirmResults)
            {
                var khachHangInvoice = db.KHACHHANG_INVOICE.SingleOrDefault(n => n.KEY == key);
                khachHangInvoice.TRANGTHAI = "CONFIRMED";
                db.Entry(khachHangInvoice).State = System.Data.Entity.EntityState.Modified;
            }
            db.SaveChanges();
            return confirmResults.Count.ToString();
        }
        [Authorize]
        public async Task<string> PhatHanhHDDT(List<GetHoaDonJoinLastInvoice> hoaDons)
        {
            //------Import và Confirm những hóa đơn đã thanh toán-------//            
            Username = db.CONFIGs.SingleOrDefault(n => n.CONFIG_NAME == "Username").CONFIG_VALUE;
            Password = db.CONFIGs.SingleOrDefault(n => n.CONFIG_NAME == "Password").CONFIG_VALUE;
            Account = db.CONFIGs.SingleOrDefault(n => n.CONFIG_NAME == "Account").CONFIG_VALUE;
            ACpass = db.CONFIGs.SingleOrDefault(n => n.CONFIG_NAME == "ACpass").CONFIG_VALUE;
            Pattern = db.CONFIGs.SingleOrDefault(n => n.CONFIG_NAME == "Pattern").CONFIG_VALUE;
            Serial = db.CONFIGs.SingleOrDefault(n => n.CONFIG_NAME == "Serial").CONFIG_VALUE;
            var soHoaDonPerTask = int.Parse(db.CONFIGs.SingleOrDefault(n => n.CONFIG_NAME == "InvoicePerRequest").CONFIG_VALUE);
            var soTaskMoiLanGoiHam = int.Parse(db.CONFIGs.SingleOrDefault(n => n.CONFIG_NAME == "RequestPerTime").CONFIG_VALUE); //Chưa dùng

            hinhThucs = db.HINHTHUCTTs.ToList();
            services = db.BANGGIAVESINHs.ToList();
            var invoices = new List<INVOICE>();
            List<string> confirmedKeys = new List<string>();

            var tasks = new List<Task>();

            if (hoaDons.Count > 0)
            {
                var soLuongTask = hoaDons.Count / soHoaDonPerTask; //Chia hết lấy được số task(request)
                var hoaDonDu = soLuongTask > 0 ? hoaDons.Count % soHoaDonPerTask : hoaDons.Count;        //Chia dư lấy được số lượng hóa đơn còn lại để chạy task cuối. Khi số lượng hóa đơn nhỏ hơn soHoaDonPerTask sẽ cho coi số lượng hóa đơn như hoaDonDu
                for (int i = 0; i < soLuongTask; i++)
                {
                    var _hoaDons = hoaDons.Skip(i * soHoaDonPerTask).Take(soHoaDonPerTask).ToList();
                    var _invoices = ImportHoaDons(_hoaDons);
                    if (_invoices.Count == 0) break;
                    invoices.AddRange(_invoices);
                    //var _importedKeys = new List<string>();
                    //foreach (var invoice in _invoices)
                    //{
                    //    _importedKeys.Add(invoice.Key.ToString());
                    //}
                }
                if (hoaDonDu > 0)
                {
                    var _hoaDons = hoaDons.Skip(hoaDons.Count - hoaDonDu).Take(hoaDonDu).ToList();
                    var _invoices = ImportHoaDons(_hoaDons);
                    if (_invoices.Count > 0)
                    invoices.AddRange(_invoices);
                    //var _importedKeys = new List<string>();
                    //foreach (var invoice in _invoices)
                    //{
                    //    _importedKeys.Add(invoice.Key.ToString());
                    //}
                }
                try
                {
                    await Task.WhenAll(tasks);
                }
                catch (Exception ex)
                {

                }

                db.INVOICEs.AddRange(invoices);
                db.SaveChanges();
            }
            return invoices.Count + "/" + hoaDons.Count;
        }
        public INVOICE khoiTaoHoaDonLuuDb(GetHoaDonJoinLastInvoice hoaDon)
        {
            var VATRate = 8;
            var chuKyNo = int.Parse(hoaDon.CHUKYNO);
            var key = "" + hoaDon.MASOCD + hoaDon.CHUKYNO + db.KHACHHANG_INVOICE.Where(n => n.CHUKYNO == chuKyNo && n.MASOCD == hoaDon.MASOCD).ToList().Count();
            var invoice = new INVOICE();
            var service = services.SingleOrDefault(n => n.IDBGVS == hoaDon.IDBGVS);
            invoice.Key = key;
            invoice.Amount = hoaDon.THANHTIENVS;
            invoice.AmountInwords = CongCu.So_chu(double.Parse(hoaDon.THANHTIENVS.ToString()));
            invoice.ArisingDate = DateTime.Now.Date;
            string soNha = hoaDon.SONHA == "" ? "" : hoaDon.SONHA + ", ";

WebMVC/Controllers/HTTTController.cs
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System;
using System.Net;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using PagedList;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.IO;
using Data;


namespace WebMVC.Controllers
{
    public class HTTTController : Controller
    {
        //
        // GET: /HTTT/
        private MTDTEntities db = new MTDTEntities();
        public ActionResult Index()
        {
            var lst_httt = db.GetHTTT().ToList();
            return View(lst_httt);
        }
        public EmptyResult ThemHTTT(string mahttt, string tenhttt)
        {
            db.Database.ExecuteSqlCommand("InsertHTTT @mahttt={0}, @tenhttt={1}", mahttt, tenhttt);
            return new EmptyResult();
        }
        public EmptyResult UpdateHTTT(string mahttt, string tenhttt)
        {
            db.Database.ExecuteSqlCommand("UpdateHTTT @mahttt={0}, @tenhttt={1}", mahttt, tenhttt);
            return new EmptyResult();
        }
        public EmptyResult XoaHTTT(string id)
        {
            db.Database.ExecuteSqlCommand("DeleteHTTT @mahttt={0}", id);
            return new EmptyResult();
        }
	}
}

WebMVC/Views/Shared/NotAllowed.cshtml
@model System.Web.Mvc.HandleErrorInfo

@{
    ViewBag.Title = "NotAllowed";
}

<h1 class="text-danger">Cảnh báo</h1>
<h2 class="text-danger">Bạn không có quyền thực hiện chức năng này.</h2>

WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <!--meta name="viewport" content="width=device-width, initial-scale=1.0"-->
    <title>@ViewBag.Title</title>
    <script src="~/Scripts/jquery-1.10.2.min.js" type="text/javascript"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/jqueryui")
    <script src="~/Scripts/jquery.form.js"></script>
    <link href="~/Content/nhiSite.css" rel="stylesheet" />
</head>
<body>
    <div class="container body-content">
        <div class="row">
            <div class="col-12">
                <div class="body-header">
                    <p> @Html.ActionLink("Quản lý Khách hàng", "Index", "Home")</p>
                </div>
                <div class="menu">
                    <ul>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                               role="button" aria-haspopup="true" aria-expanded="false">
                                QL khách hàng <img src="~/Content/Images/arrow-down.png" />
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Danh sách khách hàng", "Index", "Khachhang")</li>
                                @if (!User.IsInRole("ReadOnly"))
                                {
                                    <li>@Html.ActionLink("Import dữ liệu", "Import", "ImportExcel")</li>
                                    <li>@Html.ActionLink("Kết chuyển dữ liệu", "Index", "Ketchuyen")</li>
                                    <li>@Html.ActionLink("Chuyển sổ ghi khách hàng", "Index", "Chuyenkhachhang")</li>
                                }

                            </ul>
                        </li>
                        <!--Chức năng hóa đơn chưa sử dụng-->
                        @*@if (!User.IsInRole("ReadOnly"))
                            {
                                 <li class="dropdown">@Html.ActionLink("Hóa đơn", "Index", "Hoadon")</li>
                            }*@

                        @if (!User.IsInRole("ReadOnly"))
                        {
                    <!--Chức năng hóa đơn chưa sử dụng-->
                            <li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                                   role="button" aria-haspopup="true" aria-expanded="false">
                                    Giao hóa đơn <img src="~/Content/Images/arrow-down.png" />
                                </a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Nhập giao hóa đơn", "Index", "Giaohoadon")</li>
                                    <li>@Html.ActionLink("Xóa chỉnh hóa đơn", "Xoachinhhoadon", "Giaohoadon")</li>
                                </ul>
                            </li>



                            <li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                                   role="button" aria-haspopup="true" aria-expanded="false">
                                    Hóa đơn điện tử<img src="~/Content/Images/arrow-down.png" />
                                </a>
                                <ul class="dropdown-menu">
                                    @*<li>@Html.ActionLink("Danh sách hóa đơn điện tử", "Index", "HDDT")</li>*@
                                    <li>@Html.ActionLink("Phát hành hóa đơn điện tử", "PhatHanh", "HDDT")</li>
                                    <li>@Html.ActionLink("Hủy hóa đơn điện tử", "Huy", "HDDT")</li>
                                    <li>@Html.ActionLink("Phát hành hóa đơn tùy chỉnh", "PhatHanhHoaDonConLai", "HDDT")</li>
                                    <li>@Html.ActionLink("In phiếu biên nhận", "PhieuBienNhan", "HDDT")</li>
                                    <li>@Html.ActionLink("Lập bảng kê hóa đơn điện tử", "BangKeHoaDon", "HDDT")</li>
                                    <li>@Html.ActionLink("Cấu hình tham số HDDT", "CauHinhHDDT", "HDDT")</li>
                                </ul>
                            </li>

                            <li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                                   role="button" aria-haspopup="true" aria-expanded="false">
                                    QL danh mục <img src="~/Content/Images/arrow-down.png" />
                                </a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Hình thức thanh toán", "Index", "HTTT")</li>
                                    <li>@Html.ActionLink("Đặc điểm", "Index", "Dacdiem")</li>
                                    <li>@Html.ActionLink("Sổ ghi", "Index", "Soghi")</li>
                                    <li>@Html.ActionLink("Đường", "Index", "Duong")</li>
                                    <li>@Html.ActionLink("Khu vực", "Index", "Khuvuc")</li>
                                    <li>@Html.ActionLink("Bảng giá vệ sinh", "Index", "BGVS")</li>
                                </ul>
                            </li>
                        }
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                               role="button" aria-haspopup="true" aria-expanded="false">
                                QL tài khoản <img src="~/Content/Images/arrow-down.png" />
                            </a>
                            <ul class="dropdown-menu">
                                @if (User.IsInRole("Administrator"))
                                {
                                    <li>@Html.ActionLink("Thêm tài khoản", "Index", "Account")</li>
                                    <li>@Html.ActionLink("Quản lý người dùng", "Quyen", "Account")</li>
                                }
                                <li>@Html.ActionLink("Cập nhật tài khoản", "Nguoidung", "Account")</li>
                            </ul>
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                               role="button" aria-haspopup="true" aria-expanded="false">
                                Báo cáo <img src="~/Content/Images/arrow-down.png" />
                            </a>
                            <ul class="dropdown-menu">
                                <!--Chức năng hóa đơn chưa sử dụng-->
                                @*<li class="dropdown">
                                        <a href="" class="dropdown-toggle fly" data-toggle="dropdown"
                                           role="button" aria-haspopup="true"
                                           aria-expanded="false">Hóa đơn tồn đầu kỳ </a>
                                        <ul>
                                            <li>@Html.ActionLink("Bảng kê HĐ tồn đầu kỳ", "BangkeTondauky", "Report")</li>
                                            <li>@Html.ActionLink("Tổng hợp HĐ tồn đầu kỳ", "TonghopTondauky", "Report")</li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a href="" class="dropdown-toggle fly" data-toggle="dropdown"
                                           role="button" aria-haspopup="true"
                                           aria-expanded="false">Hóa đơn phát sinh</a>
                                        <ul>
                                            <li>@Html.ActionLink("Bảng kê HĐ phát sinh", "BangkePhatsinh", "Report")</li>
                                            <li>@Html.ActionLink("Tổng hợp HĐ phát sinh", "TonghopPhatsinh", "Report")</li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a href="" class="dropdown-toggle fly" data-toggle="dropdown"
                                           role="button" aria-haspopup="true"
                                           aria-expanded="false">Hóa đơn tồn cuối kỳ</a>
                                        <ul>
                                            <li>@Html.ActionLink("Bảng kê HĐ tồn cuối kỳ", "BangkeToncuoiky", "Report")</li>
                                            <li>@Html.ActionLink("Tổng hợp HĐ tồn cuối kỳ", "TonghopToncuoiky", "Report")</li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a href="" class="dropdown-toggle fly" data-toggle="dropdown"
                                           role="button" aria-haspopup="true"
                                           aria-expanded="false">Hóa đơn thu được hiện tại</a>
                                        <ul>
                                            <li>@Html.ActionLink("Bảng kê HĐ thu được hiện tại", "BangkeThuhientai", "Report")</li>
                                            <li>@Html.ActionLink("Tổng hợp HĐ thu được hiện tại", "TonghopThuhientai", "Report")</li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a href="" class="dropdown-toggle fly" data-toggle="dropdown"
                                           role="button" aria-haspopup="true"
                                           aria-expanded="false">Hóa đơn thu được tháng trước</a>
                                        <ul>
                                            <li>@Html.ActionLink("Bảng kê HĐ thu được tháng trước", "BangkeThuthangtruoc", "Report")</li>
                                            <li>@Html.ActionLink("Tổng hợp HĐ thu được tháng trước", "TonghopThuthangtruoc", "Report")</li>
                                        </ul>
                                    </li>*@
                                <li>@Html.ActionLink("Tiền vệ sinh từng đường", "Index", "Report")</li>
                                <li>@Html.ActionLink("Tiền vệ sinh từng khu vực", "Khuvuc", "Report")</li>
                                <li>@Html.ActionLink("Kê thu tiền vệ sinh tháng", "Thang", "Report")</li>
                                <!--Chức năng Hóa đơn chưa sử dụng-->
                                @*<li>@Html.ActionLink("Giao nhận phiếu thu VS", "Giaohoadon", "Report")</li>
                                    <li>@Html.ActionLink("Tổng hợp giao nhận VS", "ChitietGiaohoadon", "Report")</li>*@
                            </ul>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>

                            @if (Request.IsAuthenticated)
                            {
                                @Html.ActionLink(User.Identity.Name + " - Đăng xuất", "LogOut", "Home")
                            }
                            else
                            {
                                @Html.ActionLink("Đăng nhập", "LogIn", "Home")
                            }

                        </li>
                    </ul>

                </div>

                @RenderBody()
                @*<hr />*@
            </div>
        </div>
    </div>
    <div class="nhi-fade">
        <div class="nhi-spinner"></div>
    </div>
    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/bootbox")
    @Scripts.Render("~/bundles/sweetmodal")
    
    <script>
        $(function () {
            $(".jqueryui-marker-datepicker").datepicker({
                dateFormat: "dd-mm-yy",
                changeYear: true,
                firstDay: 1,
                showWeek: true,
                constrainInput: true,
                dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
                dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
                monthNames: ["T.Một", "T.Hai", "T.Ba", "T.Tư", "T.Năm", "T.Sáu", "T.Bảy", "T.Tám", "T.Chín", "T.Mười", "T.Mười Một", "T.Mười Hai"],
                weekHeader: "Tuần"
                //showOn: "button"
            }).css("display", "inline-block");
        });
    </script>
    @RenderSection("scripts", required: false)
</body>
<footer>
    <div>
        <p>
            Bản quyền &copy; 2015.VNPT Cà Mau<br />
            Xây dựng và phát triển bởi Trung tâm Công nghệ thông tin<br />
            Địa chỉ: 03, Lưu tấn Tài, Phường 5, Tp.Cà Mau, Tỉnh Cà Mau | Tel: 0290.3815888  | Fax: 0290.3825666 | Email: cntt.cmu@vnpt.vn
        </p>
    </div>
</footer>
</html>