WebMVC/Controllers/KhuvucController.cs
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System;
using System.Net;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using PagedList;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.IO;
using Data;


namespace WebMVC.Controllers
{
    public class KhuvucController : Controller
    {
        //
        // GET: /HTTT/
        private MTDTEntities db = new MTDTEntities();
        public ActionResult Index()
        {
            var lst_kv = db.KhuVucSelect().ToList();
            return View(lst_kv);
        }
        public EmptyResult ThemKhuvuc(string makhuvuc, string tenkhuvuc)
        {
            db.Database.ExecuteSqlCommand("InsertKhuvuc @makhuvuc={0}, @tenkhuvuc={1}", makhuvuc, tenkhuvuc);
            return new EmptyResult();
        }
        public EmptyResult UpdateKhuvuc(string makhuvuc, string tenkhuvuc)
        {
            db.Database.ExecuteSqlCommand("UpdateKhuvuc @makhuvuc={0}, @tenkhuvuc={1}", makhuvuc, tenkhuvuc);
            return new EmptyResult();
        }
        public EmptyResult Xoakhuvuc(string id)
        {
            db.Database.ExecuteSqlCommand("DeleteKhuvuc @makhuvuc={0}", id);
            return new EmptyResult();
        }        
	}
}

WebMVC/Views/Khuvuc/Index.cshtml
@model List<Data.KhuVucSelect_Result>

@{
    ViewBag.Title = "Danh mục Khu vực";
}
<!--Show danh sách-->
<table class="table table-hover table-striped table-bordered table-width-medium" id="tbl-lst-sms" >
    <tr class="title">
        <th colspan="2">
            <h5><img src="~/Content/Images/lr_title_icon.png" />Danh mục khu vực</h5>
        </th>
        <th style="text-align:right" colspan="3">
            @if (!User.IsInRole("ReadOnly"))
            {
                <h5 data-toggle="modal" data-target="#myModal">+Thêm mới</h5>
            }
        </th>
    </tr>
    <tr>
        <th>Mã khu vực</th>
        <th>Tên khu vực</th>
        <th>Chức năng</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td class="centertext">@item.MAKHUVUC</td>
            <td>
                @if (!User.IsInRole("ReadOnly"))
                {
                    <input type="text" value="@item.TENKHUVUC" id="txttenkhuvuc_@item.MAKHUVUC" name="txttenkhuvuc_@item.MAKHUVUC" class="form-control" onkeypress="update(this,'@item.MAKHUVUC', event)"/>
                }
                else
                {
                    @item.TENKHUVUC
                }
            </td>
            <td class="centertext">
                @if (!User.IsInRole("ReadOnly"))
                {
                    <button style="color: #428bca" class="btn btn-default btn-button" value="@item.MAKHUVUC" onclick="xoaKhuvuc('@item.MAKHUVUC')">Xóa</button>
                    @*<button class="btn btn-danger">@Html.ActionLink("Xóa", "XoaKhuvuc", new { id = item.MAKHUVUC }, new { @onclick = "return confirm('Bạn có chắc chắn muốn xóa?')", @style = "text-decoration: none; color: white" })</button>*@
                }
            </td>
        </tr>
    }
</table>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Thêm mới @ViewBag.Title</h4>
            </div>
            <div class="modal-body">
                <table class="table table-bordered" id="tbl-lst-sms">
                    <tr>
                        <td class="bluetext centertext">Mã khu vực</td>
                        <td><input placeholder="Nhập mã khu vực" id="makhuvuc" name="makhuvuc" class="form-control" /></td>
                    </tr>
                    <tr>
                        <td class="bluetext centertext">Tên khu vực</td>
                        <td><input placeholder="Nhập tên khu vực" id="tenkhuvuc" name="tenkhuvuc" class="form-control" /></td>
                    </tr>
                    <tr>
                        <td colspan="2" class="required">(*) Mã khu vực sẽ không thể thay đổi</td>
                    </tr>
                </table>
            </div>
            <div class="modal-footer">
                <button onclick="themKhuvuc()" type="button" class="btn btn-primary" data-dismiss="modal">Lưu</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
            </div>
        </div>
    </div>
</div>


<script src="~/Scripts/jquery-1.10.2.min.js" type="text/javascript"></script>
<script>
    function update(editableObj, makhuvuc, event) {
        var key = event.keyCode || event.which;
        if (key == 13) {
            bootbox.confirm({
                title: "Cập nhật thông tin",
                size: "small",
                message: "Bạn có chắc chắn muốn đổi tên khu vực này?",
                callback: function (result) { /* result is a boolean; true = OK, false = Cancel*/
                    if (result) {
                        $.ajax({
                            url: '@Url.Action("UpdateKhuvuc","Khuvuc")',
                            type: "POST",
                            data: 'makhuvuc=' + makhuvuc + '&tenkhuvuc=' + editableObj.value,
                            success: function (data) {
                                $.sweetModal({
                                    content: 'Cập nhật thành công!',
                                    icon: $.sweetModal.ICON_SUCCESS
                                });
                            },
                            error: function (xhr, ajaxOptions, thrownError) {
                                $.sweetModal({
                                    content: 'Xảy ra lỗi trong quá trình thực hiện!',
                                    icon: $.sweetModal.ICON_ERROR
                                });
                            }
                        })
                    }
                }
            });
        }
    }
    function themKhuvuc() {
        if (tenkhuvuc.value != "" && makhuvuc.value != "") {
            $.ajax({
                url: '@Url.Action("ThemKhuvuc","Khuvuc")',
                type: "POST",
                data: 'makhuvuc=' + makhuvuc.value + '&tenkhuvuc=' + tenkhuvuc.value,
                success: function (data) {
                    $.sweetModal({
                        content: 'Thêm mới thành công!',
                        icon: $.sweetModal.ICON_SUCCESS
                    });
                    window.location.reload();
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    $.sweetModal({
                        content: 'Xảy ra lỗi trong quá trình thực hiện!',
                        icon: $.sweetModal.ICON_ERROR
                    });
                }
            });
        }
    }
    function xoaKhuvuc(makhuvuc)
    {
        bootbox.confirm({
            title: "Xác nhận xóa?",
            size: "small",
            message: "Bạn có chắc chắn muốn xóa khu vực này?",
            callback: function (result) { /* result is a boolean; true = OK, false = Cancel*/
                if (result) {
                    $.ajax({
                        url: '@Url.Action("XoaKhuvuc","Khuvuc")',
                        type: "POST",
                        data: 'id=' + makhuvuc,
                        success: function (data) {
                            $.sweetModal({
                                content: 'Xóa thành công!',
                                icon: $.sweetModal.ICON_SUCCESS
                            });
                            window.location.reload();
                        },
                        error: function (xhr, ajaxOptions, thrownError) {
                            $.sweetModal({
                                content: 'Xảy ra lỗi trong quá trình thực hiện!',
                                icon: $.sweetModal.ICON_ERROR
                            });
                        }
                    });
                }
            }
        });
    }

</script>