WebMVC/Controllers/DacdiemController.cs
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System;
using System.Net;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using PagedList;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.IO;
using Data;


namespace WebMVC.Controllers
{
    public class DacdiemController : Controller
    {
        //
        // GET: /DACDIEM/
        private MTDTEntities db = new MTDTEntities();
        public ActionResult Index()
        {
            var lst_dd = db.GetDacdiem().ToList();
            return View(lst_dd);
        }
        public EmptyResult ThemDacdiem(string madacdiem, string tendacdiem)
        {
            db.Database.ExecuteSqlCommand("InsertDacdiem @madacdiem={0}, @tendacdiem={1}", madacdiem, tendacdiem);
            return new EmptyResult();
        }
        public EmptyResult UpdateDacdiem(string madacdiem, string tendacdiem)
        {
            db.Database.ExecuteSqlCommand("UpdateDacdiem @madacdiem={0}, @tendacdiem={1}", madacdiem, tendacdiem);
            return new EmptyResult();
        }

        public EmptyResult XoaDacdiem(string id)
        {
            db.Database.ExecuteSqlCommand("DeleteDacdiem @madacdiem={0}", id);
            return new EmptyResult();
        }
    }
}

WebMVC/Views/Dacdiem/Index.cshtml
@model IEnumerable<Data.GetDacdiem_Result>

@{
    ViewBag.Title = "Danh mục Đặc điểm";
}

<!--Show danh sách-->
<table class="table table-hover table-striped table-bordered table-width-medium" id="tbl-lst-sms">
    <tr class="title">
        <th colspan="2">
            <h5><img src="~/Content/Images/lr_title_icon.png" />Danh mục Đặc điểm</h5>
        </th>
        <th style="text-align:right" colspan="3">
            @if (!User.IsInRole("ReadOnly"))
            {
                <h5 data-toggle="modal" data-target="#myModal">+Thêm mới</h5>
            }
        </th>
    </tr>
    <tr>
        <th>Mã Đặc điểm</th>
        <th>Tên Đặc điểm</th>
        <th> Chức năng</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td class="centertext">@item.MADACDIEM</td>
            <td>
                @if (!User.IsInRole("ReadOnly"))
                {
                    <input type="text" value="@item.TENDACDIEM" id="txttendacdiem" name="txttendacdiem" class="form-control" onkeypress="update(this,'@item.MADACDIEM', event)" />
                }
                else
                {
                    @item.TENDACDIEM
                }
            </td>
            <td class="centertext">
                @if (!User.IsInRole("ReadOnly"))
                {
                    <button style="color: #428bca" class="btn btn-default btn-button" value="@item.MADACDIEM" onclick="xoaDacdiem('@item.MADACDIEM')">Xóa</button>
                    @*@Html.ActionLink("Xóa", "XoaDacdiem", new { id = item.MADACDIEM}, new { @onclick = "return confirm('Bạn có chắc chắn muốn xóa?')" })*@
                }
            </td>
        </tr>
    }
</table>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">@ViewBag.Title</h4>
            </div>
            <div class="modal-body">
                <table class="table table-bordered" id="tbl-lst-sms">
                    <tr>
                        <td class="bluetext centertext">Mã đặc điểm</td>
                        <td><input placeholder="Nhập mã đặc điểm" id="madacdiem" name="madacdiem" class="form-control" /></td>
                    </tr>
                    <tr>
                        <td class="bluetext centertext">Tên đặc điểm</td>
                        <td><input placeholder="Nhập tên đặc điểm" id="tendacdiem" name="tendacdiem" class="form-control" /></td>
                    </tr>
                    <tr>
                        <td colspan="2" class="required">(*) Mã đặc điểm sẽ không thể thay đổi</td>
                    </tr>
                </table>               
            </div>
            <div class="modal-footer">
                <button onclick="themDacdiem()" type="button" class="btn btn-primary" data-dismiss="modal">Lưu</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
            </div>
        </div>
    </div>
</div>


<script src="~/Scripts/jquery-1.10.2.min.js" type="text/javascript"></script>
<script>
    function update(editableObj, madacdiem, event) {
        var key = event.keyCode || event.which;
        if (key == 13) {
            bootbox.confirm({
                title: "Cập nhật thông tin",
                size: "small",
                message: "Bạn có chắc chắn muốn đổi tên đặc điểm này?",
                callback: function (result) { /* result is a boolean; true = OK, false = Cancel*/
                    if (result) {
                        $.ajax({
                            url: '@Url.Action("UpdateDacdiem","Dacdiem")',
                            type: "POST",
                            data: 'madacdiem=' + madacdiem + '&tendacdiem=' + editableObj.value,
                            success: function (data) {
                                $.sweetModal({
                                    content: 'Cập nhật thành công!',
                                    icon: $.sweetModal.ICON_SUCCESS
                                });
                            },
                            error: function (xhr, ajaxOptions, thrownError) {
                                $.sweetModal({
                                    content: 'Xảy ra lỗi trong quá trình thực hiện!',
                                    icon: $.sweetModal.ICON_ERROR
                                });
                            }
                        })
                    }
                }
            });
        }
    }
    
    function themDacdiem() {
        if (madacdiem.value != "" && tendacdiem.value != "") {
            $.ajax({
                url: '@Url.Action("ThemDacdiem","Dacdiem")',
                type: "POST",
                data: 'madacdiem=' + madacdiem.value + '&tendacdiem=' + tendacdiem.value,
                success: function (data) {
                    $.sweetModal({
                        content: 'Thêm mới thành công!',
                        icon: $.sweetModal.ICON_SUCCESS
                    });
                    window.location.reload();
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    $.sweetModal({
                        content: 'Xảy ra lỗi trong quá trình thực hiện!',
                        icon: $.sweetModal.ICON_ERROR
                    });
                    //alert(xhr.status);
                    //alert(thrownError);
                }
            });
        }
    }
    function xoaDacdiem(madacdiem) {
        bootbox.confirm({
            title: "Xác nhận xóa?",
            size: "small",
            message: "Bạn có chắc chắn muốn xóa đặc điểm này?",
            callback: function (result) { /* result is a boolean; true = OK, false = Cancel*/
                if (result) {
                    $.ajax({
                        url: '@Url.Action("XoaDacdiem","Dacdiem")',
                        type: "POST",
                        data: 'id=' + madacdiem,
                        success: function (data) {
                            $.sweetModal({
                                content: 'Xóa thành công!',
                                icon: $.sweetModal.ICON_SUCCESS
                            });
                            window.location.reload();
                        },
                        error: function (xhr, ajaxOptions, thrownError) {
                            $.sweetModal({
                                content: 'Xảy ra lỗi trong quá trình thực hiện!',
                                icon: $.sweetModal.ICON_ERROR
                            });
                        }
                    });
                }
            }
        });
    }
</script>