WebMVC/Controllers/GiaohoadonController.cs
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System;
using System.Net;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using PagedList;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.IO;
using Data;
using Business;

namespace WebMVC.Controllers
{
    public class GiaohoadonController : Controller
    {
        //
        // GET: /Giaohoadon/
        private MTDTEntities db = new MTDTEntities();

        [Authorize]
        public ActionResult Index()
        {
            //ViewBag.KhuvucList = new SelectList(db.KhuVucSelect(), "MAKHUVUC", "TENKHUVUC");
            ViewBag.NamList = new SelectList(db.GetNam(), "NAM", "NAM");
            if (User.IsInRole("ReadOnly"))
                return Content("<script language='javascript' type='text/javascript'>alert('Bạn không có quyền thực hiện thao tác này')</script>");
            else
                return View(Business.KHACHHANG.Index());
            /*if(!User.IsInRole("Administrator"))
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);*/
        }
        //Xu ly Ajax dropdownlist
        public JsonResult getChukybyNam(string nam)
        {
            var result = db.getChukybyNam(nam); //call store procedure getKhuvucbyChuky duoc update to model
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public JsonResult getKhuvuc(string chuky)
        {
            var result = db.getKhuvucbyChuky(chuky);
            return Json(result, JsonRequestBehavior.AllowGet);
        }        
        public JsonResult getSoghi(string khuvuc, string chuky)
        {  
            var result = db.getSoghiGiaohoadon(chuky, khuvuc);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public JsonResult getLangiaobyMakhuvuc(string chuky, string khuvuc)
        {
            var result = db.getLangiaobyMakhuvuc(chuky, khuvuc);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [Authorize]
        public EmptyResult Giaohoadon(string chuky, string khuvuc, string[] masoghi, int[] tuseri, int[] denseri, int langiao, int[] sohd, decimal[] sotien)
        {
            string tendangnhap = User.Identity.Name.ToString();
            var i = 0;
            for (i = 0; i< masoghi.Count() ; i++)
            {
                db.Database.ExecuteSqlCommand("InsertGiaohoadon @chuky={0},@langiao={1},@soghi={2},@tuseri={3},@denseri={4},@tendangnhap={5},@sohd={6},@sotien={7}", chuky, langiao, masoghi[i], tuseri[i], denseri[i], tendangnhap, sohd[i], sotien[i]);
            }
            return new EmptyResult();
            //return Content("<script language='javascript' type='text/javascript'>alert('Lưu thành công');window.location.href='~/../Index'</script>");
        }
        [Authorize]
        public ActionResult Xoachinhhoadon()
        {
            //ViewBag.ChukyList = new SelectList((from a in db.GIAOHOADONs select new {CHUKY = a.CHUKY, TENCHUKY = a.CHUKY.Substring(4,2)+"/"+a.CHUKY.Substring(0,4)}).Distinct(), "CHUKY", "TENCHUKY");
            //ViewBag.ChukyList = new SelectList(db.getChukyGiaohoadon(), "CHUKY", "TENCHUKY");
            ViewBag.NamList = new SelectList(db.GetNam(), "NAM", "NAM");
            if (User.IsInRole("ReadOnly"))
                return Content("<script language='javascript' type='text/javascript'>alert('Bạn không có quyền thực hiện thao tác này')</script>");
            else
                return View();
        }
        public JsonResult getSoghi_Xoachinh(string chuky, string khuvuc, int langiao)
        {
            var result = db.getSoghiXoachinh(chuky, khuvuc, langiao);
            return Json(result, JsonRequestBehavior.AllowGet);
        }        
        public EmptyResult Luuxoachinh(string[] idctghd, int[] xoachinhhd, decimal[] xoachinhst, int[] tuseri, int[] denseri, int[] giaohd, decimal[] giaost)
        {
            var i = 0;
            for (i = 0; i < idctghd.Count(); i++)
            {
                db.Database.ExecuteSqlCommand("Xoachinhhoadon @idctghd={0},@xoachinhhd={1},@xoachinhst={2}, @tuseri={3}, @denseri={4}, @giaohd={5}, @giaost={6}", idctghd[i], xoachinhhd[i], xoachinhst[i], tuseri[i], denseri[i], giaohd[i], giaost[i]);
            }
            return new EmptyResult();
            //return Content("<script language='javascript' type='text/javascript'>alert('Lưu thành công');window.location.href='~/../Xoachinhhoadon'</script>");
        }
        public EmptyResult Xoa(int idctghd)
        {
            db.Database.ExecuteSqlCommand("DeleteCTGHD @idctghd={0}", idctghd);
            return new EmptyResult();
        }

	}
}

WebMVC/Views/Giaohoadon/Index.cshtml
@model IEnumerable<Data.CHUKY_KHUVUC>

@{
    ViewBag.Title = "Giao hóa đơn";
}

    <div class="title">
        <h5><img src="~/Content/Images/lr_title_icon.png" />Nhập giao hóa đơn</h5>
    </div>
    <table class="table table-index table-hover">
        <tr>
            <td colspan="2"></td>
        </tr>
        <tr>
            <td><b>Năm</b> @*@Html.DropDownList("nam", (SelectList)ViewBag.NamList, "Chọn năm", new { @class = "form-control" })*@
                @{
                    string currentYear = DateTime.Now.Year.ToString();
                }
                <input id="nam" name="nam" class="form-control" value="@currentYear" placeholder="Nhập năm" />
            </td>
            <td>
                <b>Tháng</b>
                <select class="form-control" id="chuky" name="chuky">
                    <option value="0">Chọn tháng</option>
                </select>
            </td>
            <td>
                <b>Khu vực</b>
                <select class="form-control" id="khuvuc" name="khuvuc">
                    <option value="0">Chọn khu vực</option>
                </select>
            </td>
        </tr>
    </table>
    <div id="dssoghi"></div>
    <div class="col-md-3">
        <table class="table table-index table-hover">
            <tr>
                <td>
                    <div class="input-group">
                        <input id="langiao" name="langiao" class="form-control" placeholder="Nhập Lần giao" />
                        <span class="input-group-btn"><button id="submit" name="submit" class="btn btn-primary">Lưu</button></span>
                    </div>
                </td>
            </tr>
        </table>
    </div>
    
    
    
    <script src="~/Scripts/jquery-1.10.2.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {

            function getChuky(nam) {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("getChukybyNam","Giaohoadon")',
                    dataType: "json",
                    data: { nam: nam },
                    success: function (data) {
                        $("#chuky").html("");
                        $("#khuvuc").html("");
                        $("#chuky").append('<option value="0">Chọn tháng</option>');
                        $("#khuvuc").append('<option value="0">Chọn khu vực</option>');
                        $.each(data, function (i, data2) {
                            $("#chuky").append('<option value= "' + data2.CHUKY + '">' + data2.TENCHUKY + '</option>');
                        });
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(xhr.status);
                        alert(thrownError);
                    }
                });
            }

            var nam = $("#nam").val().toString();
            getChuky(nam);


            $("#nam").keyup(function () {
                var nam = $("#nam").val().toString();
                getChuky(nam);
            });
            $("#chuky").change(function () {
                var chuky = $("#chuky").val().toString();
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("getKhuvuc","Giaohoadon")',
                    dataType: "json",
                    data: { chuky: chuky },
                    success: function (data) {
                        $("#khuvuc").html("");
                        $("#khuvuc").append('<option value="0">Chọn khu vực</option>');
                        $.each(data, function (i, data2) {
                            $("#khuvuc").append('<option value= "' + data2.MAKHUVUC + '">' + data2.TENKHUVUC + '</option>');
                        });
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(xhr.status);
                        alert(thrownError);
                    }
                });
            });

            $("#khuvuc").change(function () {
                var chuky = $("#chuky").val().toString();
                var khuvuc = $("#khuvuc").val().toString();
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("getSoghi","Giaohoadon")',
                    dataType: "json",
                    data: { khuvuc: khuvuc, chuky: chuky },
                    success: function (data) {
                        //alert("abc");
                        $("#dssoghi").html("");
                        if (data.length != 0) {
                            var str = "";
                            str += "<table id='soghi' table class='table table-hover table-striped' id='tbl-lst-sms'>";
                            str += "<thead><tr><th><input type='checkbox' id='chkAll' name='chkAll' class='chkAll' /></th>";
                            str += "<th>Sổ ghi</th><th>Số HĐ</th><th>Số tiền</th><th>Từ số sêri</th><th>Đến số sêri</th></tr></thead>";
                            str += "<tbody>";
                            for (i = 0; i < data.length; i++) {
                                str += "<tr>";
                                str += "<td><input type='checkbox' name='chk[]' class='chkElements' value='" + data[i].MASOGHI + "' /></td>";
                                str += "<td>" + data[i].TENSOGHI + "</td>";
                                str += "<td><input value='" + data[i].SOHD + "' placeholder='Số hóa đơn' class='form-control' id='txtsohd_" + data[i].MASOGHI + "' name='txtsohd_" + data[i].MASOGHI + "'/></td>";
                                str += "<td><input value='" + data[i].SOTIEN + "' placeholder='Số tiền' class='form-control' id='txtsotien_" + data[i].MASOGHI + "' name='txtsotien_" + data[i].MASOGHI + "'/></td>";
                                str += "<td><input placeholder='Từ số sêri' class='form-control' id='txttuseri_" + data[i].MASOGHI + "' name='txttuseri_" + data[i].MASOGHI + "'/></td>";
                                str += "<td><input placeholder='Đến số sêri' class='form-control' id='txtdenseri_" + data[i].MASOGHI + "' name='txtdenseri_" + data[i].MASOGHI + "'/></td>";
                                str += "</tr>";
                            }
                            //str += "<tr><td><button id='submit' onclick='a()' name='submit' class='btn btn-primary'>Lưu</button></td></tr>";
                            str += "</tbody>";
                            str += "</table>";
                            $('#dssoghi').html(str);
                        }
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(xhr.status);
                        alert(thrownError);
                    }
                });
            });
            $(document).on('click', 'input.chkAll', function () {
                var state = $('.chkAll').prop('checked');
                $('.chkElements').prop('checked', state);
            });


            $("#submit").click(function () {
                var checked = [];
                var tuseri = [];
                var denseri = [];
                var sohd = [];
                var sotien = [];
                $("input[name='chk[]']:checked").each(function () {
                    var masoghi = $(this).val();
                    checked.push(($(this).val()));

                    if ($("#txttuseri_" + masoghi).val() != "") {
                        tuseri.push(parseInt($("#txttuseri_" + masoghi).val()));
                    }
                    else {
                        tuseri.push(0);
                    }
                    if ($("#txtdenseri_" + masoghi).val() != "") {
                        denseri.push(parseInt($("#txtdenseri_" + masoghi).val()));
                    }
                    else {
                        denseri.push(0);
                    }
                    if ($("#txtsohd_" + masoghi).val() != "") {
                        sohd.push(parseInt($("#txtsohd_" + masoghi).val()));
                    }
                    else {
                        sohd.push(0);
                    }
                    if ($("#txtsotien_" + masoghi).val() != "") {
                        sotien.push(parseInt($("#txtsotien_" + masoghi).val()));
                    }
                    else {
                        sotien.push(0);
                    }

                });

                /*$("input[name='chk[]']:not(:checked)").each(function ()
                {
                    notchecked.push(($(this).val()));
                });*/

                if (langiao.value != "") {
                    //alert(sohd+sotien);
                    $.ajax({
                        type: "POST",
                        traditional: true,
                        url: '@Url.Action("Giaohoadon","Giaohoadon")',
                        data: { "chuky": chuky.value, "khuvuc": khuvuc.value, "langiao": langiao.value, "masoghi": checked, "tuseri": tuseri, "denseri": denseri, "sohd": sohd, "sotien": sotien },
                        cache: false,
                        success: function (data) {
                            alert("Lưu thành công");
                        },
                        error: function (xhr, ajaxOptions, thrownError) {
                            alert("Không thể lưu");
                        }
                    });
                }
            });

        });
    </script>